channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterhub-base==2.3.1
  - jupyterhub-singleuser=2.3.1
  - numpy
  - matplotlib
  - scipy
  - pandas
  - pymef
  - tqdm
  - s3fs
  - awscli
  - scikit-learn
